rpm: Remove bbappend since the patch is already applied for 5.4.14
Build results in following error:

ERROR: Command Error: exit status: 1  Output:
Patch 0001-define-EM_AARCH64.patch is already applied; check your series file
ERROR: Function failed: patch_do_patch

Signed-off-by: Bogdan Purcareata <bogdan.purcareata@nxp.com>